name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  testing:
    name: Testing on Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22, 20]
    steps:
      - name: Checking out
        uses: actions/checkout@v5

      - name: Use Node.js v${{ matrix.node }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install NPM dependencies
        run: npm ci

      - name: Check lint
        run: npm run lint

      - name: Check build
        run: npm run build

      - name: Run NPM tests
        run: npm test

      - name: Check examples
        run: npm run examples
